### ISSUE TITLE
Auto completion doesn't work for .yml in idea 2020.3

### ISSUE THREAD

**Issue by tangyb828** [1tontech/intellij-spring-assistant#18]
Start error report.

`com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:752)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:704)
	at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:463)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:296)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:105)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:93)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:30)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:86)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClasses(JavaFileManagerImpl.java:73)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClasses(PsiElementFinderImpl.java:62)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClassesWithoutJvmFacade(JavaPsiFacadeImpl.java:157)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClassesWithJvmFacade(JavaPsiFacadeImpl.java:128)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClasses(JavaPsiFacadeImpl.java:120)
	at com.intellij.psi.impl.file.PsiPackageImpl.findAllClasses(PsiPackageImpl.java:203)
	at com.intellij.psi.impl.file.PsiPackageImpl.getCachedClassesByName(PsiPackageImpl.java:193)
	at com.intellij.psi.impl.file.PsiPackageImpl.findClassByShortName(PsiPackageImpl.java:270)
	at com.intellij.psi.impl.file.PsiPackageImpl.processDeclarations(PsiPackageImpl.java:310)
	at com.intellij.psi.impl.source.resolve.JavaResolveUtil.processImplicitlyImportedPackages(JavaResolveUtil.java:239)
	at com.intellij.psi.impl.source.JavaDummyHolder.processDeclarations(JavaDummyHolder.java:112)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:61)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:40)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:207)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:136)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:489)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:522)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:44)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:375)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:368)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:179)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:221)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:198)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:179)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:806)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:798)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:774)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:423)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:417)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:352)
	at com.intellij.psi.impl.source.resolve.ClassResolverProcessor.<init>(ClassResolverProcessor.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:488)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:522)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:44)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:375)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:368)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:179)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:221)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:198)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:179)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:806)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:798)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:774)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:423)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:417)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:352)
	at com.intellij.psi.impl.source.resolve.ClassResolverProcessor.<init>(ClassResolverProcessor.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:488)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:522)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:44)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:375)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:368)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:179)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:221)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:198)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:179)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:806)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:798)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:774)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:423)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:417)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:352)
	at com.intellij.psi.impl.source.resolve.ClassResolverProcessor.<init>(ClassResolverProcessor.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:488)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:522)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:44)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:375)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:368)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:179)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:221)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:198)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:179)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:806)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:798)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:774)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:423)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:417)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:352)
	at com.intellij.psi.impl.source.resolve.ClassResolverProcessor.<init>(ClassResolverProcessor.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:488)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:522)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:44)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:375)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:368)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:179)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:221)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:198)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:179)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:806)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:798)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:774)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:423)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:417)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:352)
	at com.intellij.psi.impl.source.resolve.ClassResolverProcessor.<init>(ClassResolverProcessor.java:55)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:488)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:44)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:375)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:368)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:179)
	at com.intellij.openapi.util.Computable.get(Computable.java:17)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$3(ResolveCache.java:221)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:198)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:179)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:806)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:798)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:774)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:423)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:417)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:177)
	at in.oneton.idea.spring.assistant.plugin.misc.PsiCustomUtil.isValidType(PsiCustomUtil.java:393)
	at in.oneton.idea.spring.assistant.plugin.misc.PsiCustomUtil.safeGetValidType(PsiCustomUtil.java:106)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.updateGroupType(MetadataNonPropertySuggestionNode.java:544)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.setGroup(MetadataNonPropertySuggestionNode.java:445)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.addGroupsToIndex(SuggestionServiceImpl.java:578)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.buildMetadataHierarchy(SuggestionServiceImpl.java:459)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.processContainers(SuggestionServiceImpl.java:412)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.reindexModule(SuggestionServiceImpl.java:449)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$null$2(SuggestionServiceImpl.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:860)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reIndex$3(SuggestionServiceImpl.java:110)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by kcotzen** [comment]
Hi guys, same problem here:
Version 2020.3 Community

"No suggestions" message in every yml file.

(looks like this project was abandoned :(  )

**Comment by dayanfcosta** [comment]
This project seems to be abandoned, what I could find is that updating gradle plugin from version 4.4 to the latest one, removing the dependency of Lombok Plugin and, compiling the code to java 11 should solve this problem. I'll work hard on these issues this week and, as soon as I have any update I'll let you know. Maybe will be necessary a fork and manual installation of the plugin on Intellij 2020.3

**Comment by dayanfcosta** [comment]
I've tried hard these days and couldn't get any advance on this. Basically is update the project to the last version of Gradle and compile it on Java 11 (required by IntellijCE 2020.3) but I'm getting an error that I couldn't find the solution yet. Feel free to test this approach also, fast we fix this, best.

EDIT: To give you more context for further solutions for this plugin, I'm getting the following errors:

When synchronizing Gradle:
```
Failed to notify project evaluation listener.
   > org/gradle/api/publish/ivy/internal/artifact/DefaultIvyArtifact
```

After updating the project Gradle version to 6.7.1 and tried to execute a `./gradlew build --stacktrace` I got the following error at the bottom of the stack:

```
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/publish/ivy/internal/artifact/DefaultIvyArtifact
        at org.jetbrains.intellij.dependency.IdeaDependencyManager.resolveRemote(IdeaDependencyManager.groovy:50)
        at org.jetbrains.intellij.dependency.IdeaDependencyManager$resolveRemote.call(Unknown Source)
        at org.jetbrains.intellij.IntelliJPlugin.configureIntellijDependency(IntelliJPlugin.groovy:111)
        at org.jetbrains.intellij.IntelliJPlugin.configureProjectAfterEvaluate(IntelliJPlugin.groovy:93)
        at org.jetbrains.intellij.IntelliJPlugin$_configureTasks_closure2.doCall(IntelliJPlugin.groovy:81)
```

In the `build.gradle` I changed the following:

```

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

plugins {
    id "org.jetbrains.intellij" version "0.6.3"
    id "org.jetbrains.grammarkit" version "2020.3"
}

intellij {
    version 'IC-2020.3'
    plugins = ['properties', 'yaml', 'maven', 'gradle']
}
```

You can get the full Gradle report at https://scans.gradle.com/s/u7jhfa2n2w7qw

**Comment by wallysoncarvalho** [comment]
Same problem here !

**Comment by eltonsandre** [comment]
Hello guys,

I was having the same problem,
unfortunately, the project appears to be no longer being maintained and / or receiving updates.
So, I decided to explore and realized that, for new versions of the IDE, some API features were discontinued and some removed, some dependencies were also built in JDK 11.
As I wanted to continue using the plugin, I forked and fixed the bug and refactored it for new versions of Intellij CE.

I hope it helps!
please give me feedback.

plugin with fix -> [intellij-spring-assistant-1.0.0.zip](https://github.com/1tontech/intellij-spring-assistant/files/5901962/intellij-spring-assistant-1.0.0.zip) 

[https://github.com/eltonsandre/intellij-spring-assistant/blob/main/CHANGELOG.md](https://github.com/eltonsandre/intellij-spring-assistant/blob/main/CHANGELOG.md)

**Comment by nutbutterfly** [comment]
> Hello guys,
> 
> I was having the same problem,
> unfortunately, the project appears to be no longer being maintained and / or receiving updates.
> So, I decided to explore and realized that, for new versions of the IDE, some API features were discontinued and some removed, some dependencies were also built in JDK 11.
> As I wanted to continue using the plugin, I forked and fixed the bug and refactored it for new versions of Intellij CE.
> 
> I hope it helps!
> please give me feedback.
> 
> plugin with fix -> [intellij-spring-assistant-1.0.0.zip](https://github.com/1tontech/intellij-spring-assistant/files/5901962/intellij-spring-assistant-1.0.0.zip)
> 
> https://github.com/eltonsandre/intellij-spring-assistant/blob/refactor/update-ide-versions/CHANGELOG.md

Thanks @eltonsandre for workaround.
It's work!!!

**Comment by spencercjh** [comment]
> > Hello guys,
> > I was having the same problem,
> > unfortunately, the project appears to be no longer being maintained and / or receiving updates.
> > So, I decided to explore and realized that, for new versions of the IDE, some API features were discontinued and some removed, some dependencies were also built in JDK 11.
> > As I wanted to continue using the plugin, I forked and fixed the bug and refactored it for new versions of Intellij CE.
> > I hope it helps!
> > please give me feedback.
> > plugin with fix -> [intellij-spring-assistant-1.0.0.zip](https://github.com/1tontech/intellij-spring-assistant/files/5901962/intellij-spring-assistant-1.0.0.zip)
> > https://github.com/eltonsandre/intellij-spring-assistant/blob/refactor/update-ide-versions/CHANGELOG.md
> 
> Thanks @eltonsandre for workaround.
> It's work!!!

God bless u, you are our hero.

**Comment by spencercjh** [comment]
> Hello guys,
> 
> I was having the same problem,
> unfortunately, the project appears to be no longer being maintained and / or receiving updates.
> So, I decided to explore and realized that, for new versions of the IDE, some API features were discontinued and some removed, some dependencies were also built in JDK 11.
> As I wanted to continue using the plugin, I forked and fixed the bug and refactored it for new versions of Intellij CE.
> 
> I hope it helps!
> please give me feedback.
> 
> plugin with fix -> [intellij-spring-assistant-1.0.0.zip](https://github.com/1tontech/intellij-spring-assistant/files/5901962/intellij-spring-assistant-1.0.0.zip)
> 
> https://github.com/eltonsandre/intellij-spring-assistant/blob/main/CHANGELOG.md

God bless u, you are our hero.

**Comment by xishian** [comment]
When I update IDEA to 2021.1, this plugin cannot work. So I try to fix it by editing plugin.xml, it works for me!
First decompress the zip file, and then, update this file: intellij-spring-assistant-1.0.0/lib/intellij-spring-assistant-1.0.0.jar!/META-INF/plugin.xml, line: 
`<idea-version since-build="203.7148" until-build="203.*"/>` to `<idea-version since-build="203.7148" until-build="211.*"/>`
and package the files again.

**Comment by eltonsandre** [comment]
Hello guys,

I generated a fix patch with compatibility for the new version of intellij. I will try whenever possible to keep the new versions compatible with the plugin. The versions will be available in the main branch -> ./dist/intellij-spring-assistant-*.jar.
[intellij-spring-assistant-1.0.1 - idea version 211.+ ](https://github.com/eltonsandre/intellij-spring-assistant/blob/main/dist/intellij-spring-assistant-1.0.1.zip)

Some ideas / improvements are generating other resources, and I'm trying to implement them as much as possible. If you want to give the launch candidate a chance and give feedback, it would be great! 😄 [intellij-spring-assistant-1.2.0-RC.2](https://github.com/eltonsandre/intellij-spring-assistant/blob/feature/link-to-properties/dist/intellij-spring-assistant-1.2.0-RC.2.zip)

maybe we can think of a better and collaborative way to maintain this plugin.

**Comment by sonurepos** [comment]
Hi all,
same error ia also faced but then I changed the version of spring parent from 2.5.2 to 2.5.1 and build it again through maven ,
its working then

**Comment by superleeyom** [comment]
hi @eltonsandre , thank you for your effort, my idea ce version is 2021.2.1, When I use the `intellij-spring-assistant-1.0.2.zip` version of the plugin to open a project, some errors appeared：
![image](https://user-images.githubusercontent.com/22115219/133542293-8f5d4fd8-7918-4989-b8c2-f25c6e2e9861.png)
Can you help me take a look? thanks

**Comment by superleeyom** [comment]
@eltonsandre 
I use this version later, it can be used perfectly, thank you！！！
[intellij-spring-assistant-1.2.0-RC.4.zip](https://github.com/eltonsandre/intellij-spring-assistant/blob/feature/link-to-properties/dist/intellij-spring-assistant-1.2.0-RC.4.zip)

**Comment by cheng6563** [comment]
@eltonsandre 
thanks!!!
Is it possible for this fork version to be put on the Marketplace?

**Comment by surbhisingh2048** [comment]
@eltonsandre 
Thanks a lot! It works :)

**Comment by superleeyom** [comment]
@eltonsandre 
There is a UI display issue here，When I create a new project，plugin version is 1.0.3，idea version is 2021.3 CE，thanks
<img width="980" alt="iShot2021-12-15 14 48 17" src="https://user-images.githubusercontent.com/22115219/146137706-29bdb9e9-99da-45cf-ab1d-9c4a7d7933b8.png">

**Comment by eltonsandre** [comment]
https://github.com/eltonsandre/intellij-spring-assistant/releases/tag/1.2.0 [fix+new features]

https://plugins.jetbrains.com/plugin/18622-spring-initializr-and-assistant
